export type { Score } from "./score";
export { winChance } from "./score";
export type { Swing } from "./swing";
export { BLUNDER, COOLDOWN, detectSwing, isQuiet } from "./swing";
export type { Observer, Verdict } from "./observer";
export { createObserver, NODES } from "./observer";
export { pickRemark } from "./pick";
export type { Remark } from "./remark";
export { REMARKS } from "./remark";
export { PAUSE, pauseFor } from "./pause";
export type { Spoken } from "./react";
export { farewell, greet, LATE, react } from "./react";
