name: Deploy

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        uses: dragunovartem99/pipes/.github/workflows/deploy-vps.yaml@v1.2.0
        with:
            strategy: release
            setup: node
            llvm-version: "22"
            build: npm run build
            upload: dist/ Caddyfile deploy.sh
            url: https://chess-animals.com
        secrets: inherit
